### ISSUE TITLE
A user should be able to register on the site

### ISSUE THREAD

**Issue by hecerinc** [hecerinc/retoactua#2]

**Comment by katiearriagam** [comment]
Missing:
- Validate email does not already exist in DB
- Add user in DB
- Success message
- Retrieve existing teams from DB for team field
- @hecerinc -> do we need team's approval?
- nice to have: confirmation email

**Comment by hecerinc** [comment]
El primero ya se checa en el server side https://github.com/hecerinc/retoactua/blob/master/src/Model/Table/UsersTable.php#L102

Team approval would be nice.  Added as #28

**Comment by hecerinc** [comment]
Closing this one in favour of more specific ones.
